import type { Kameti, Member, Payment } from "@/types/database";

// ─── Types ────────────────────────────────────────────────────────────────────
interface ReportData {
  kameti: Kameti;
  members: Member[];
  payments: Payment[];
  currentMonth: number;
  monthName: string;
}

// ─── Colour palette ───────────────────────────────────────────────────────────
const GREEN       = [22, 163, 74]   as [number, number, number]; // #16a34a
const GREEN_LIGHT = [240, 253, 244] as [number, number, number]; // #f0fdf4
const GREEN_MID   = [187, 247, 208] as [number, number, number]; // #bbf7d0
const AMBER       = [202, 138, 4]   as [number, number, number]; // #ca8a04
const AMBER_LIGHT = [255, 251, 235] as [number, number, number]; // #fffbeb
const RED         = [220, 38, 38]   as [number, number, number]; // #dc2626
const RED_LIGHT   = [254, 242, 242] as [number, number, number]; // #fef2f2
const GRAY_900    = [17, 24, 39]    as [number, number, number]; // #111827
const GRAY_600    = [75, 85, 99]    as [number, number, number]; // #4b5563
const GRAY_400    = [156, 163, 175] as [number, number, number]; // #9ca3af
const GRAY_100    = [243, 244, 246] as [number, number, number]; // #f3f4f6
const WHITE       = [255, 255, 255] as [number, number, number];

// ─── Helpers ──────────────────────────────────────────────────────────────────
function slugify(str: string) {
  return str.replace(/[^a-z0-9]/gi, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

function formatPKR(amount: number) {
  return `PKR ${amount.toLocaleString("en-PK")}`;
}

// ─── Main generator ───────────────────────────────────────────────────────────
export async function generateReportPDF(data: ReportData): Promise<void> {
  // Dynamic import — keeps jsPDF out of the initial bundle
  const { default: jsPDF } = await import("jspdf");

  const { kameti, members, payments, currentMonth, monthName } = data;

  // Filter payments for this month
  const thisMonthPayments = payments.filter((p) => p.month_number === currentMonth);
  const paidCount  = thisMonthPayments.filter((p) => p.status === "paid").length;
  const totalCount = thisMonthPayments.length;
  const totalCollected = paidCount * kameti.monthly_amount;

  // Page setup — A4
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PW = 210; // page width mm
  const PH = 297; // page height mm
  const ML = 14;  // margin left
  const MR = 14;  // margin right
  const CW = PW - ML - MR; // content width

  let y = 0; // current Y cursor

  // ── WATERMARK (drawn first, behind everything) ────────────────────────────
  doc.saveGraphicsState();
  doc.setGState(new (doc as any).GState({ opacity: 0.04 }));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(52);
  doc.setTextColor(...GRAY_900);
  // Rotate 45° around page centre
  const cx = PW / 2;
  const cy = PH / 2;
  doc.text("Generated by KametiPro", cx, cy, {
    align: "center",
    angle: 45,
  });
  doc.restoreGraphicsState();

  // ── HEADER BAND ───────────────────────────────────────────────────────────
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, PW, 28, "F");

  // Logo circle
  doc.setFillColor(...GREEN_LIGHT);
  doc.circle(ML + 7, 14, 7, "F");
  doc.setFillColor(...GREEN);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...GREEN);
  // Rupee symbol inside circle
  doc.setTextColor(...GREEN);
  doc.setFillColor(255, 255, 255);
  doc.circle(ML + 7, 14, 5.5, "F");
  doc.setTextColor(...GREEN);
  doc.setFontSize(8);
  doc.text("₨", ML + 7, 16.5, { align: "center" });

  // App name
  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("KametiPro", ML + 17, 12);

  // Tagline
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(187, 247, 208); // green-200
  doc.text("Smart Kameti Management — Aap Ki Kameti, Hamare Haath Mein", ML + 17, 19);

  // Date generated (top right)
  const dateStr = new Date().toLocaleDateString("en-PK", {
    day: "2-digit", month: "short", year: "numeric",
  });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(187, 247, 208);
  doc.text(`Generated: ${dateStr}`, PW - MR, 10, { align: "right" });

  y = 36;

  // ── KAMETI INFO CARD ──────────────────────────────────────────────────────
  doc.setFillColor(...GREEN_LIGHT);
  doc.roundedRect(ML, y, CW, 22, 3, 3, "F");
  doc.setDrawColor(...GREEN_MID);
  doc.setLineWidth(0.4);
  doc.roundedRect(ML, y, CW, 22, 3, 3, "S");

  // Left: kameti name + month
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...GRAY_900);
  doc.text(kameti.name, ML + 5, y + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY_600);
  doc.text(`${monthName}  ·  Month ${currentMonth} of ${kameti.total_months}`, ML + 5, y + 15);

  // Right: total pool pill
  doc.setFillColor(...AMBER_LIGHT);
  doc.roundedRect(PW - MR - 46, y + 4, 46, 14, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...AMBER);
  doc.text("Total Pool", PW - MR - 23, y + 9.5, { align: "center" });
  doc.setFontSize(9.5);
  doc.text(formatPKR(kameti.total_pool), PW - MR - 23, y + 15.5, { align: "center" });

  y += 30;

  // ── DIVIDER ───────────────────────────────────────────────────────────────
  doc.setDrawColor(...GREEN_MID);
  doc.setLineWidth(0.5);
  doc.line(ML, y, PW - MR, y);
  y += 6;

  // ── TABLE HEADER ──────────────────────────────────────────────────────────
  const COL = {
    num:    { x: ML,       w: 8  },
    name:   { x: ML + 8,   w: 62 },
    phone:  { x: ML + 70,  w: 42 },
    amount: { x: ML + 112, w: 36 },
    status: { x: ML + 148, w: 34 },
  };
  const ROW_H = 9;

  // Header background
  doc.setFillColor(...GREEN);
  doc.roundedRect(ML, y, CW, ROW_H, 2, 2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...WHITE);
  doc.text("#",             COL.num.x    + COL.num.w    / 2, y + 6, { align: "center" });
  doc.text("Member Name",   COL.name.x   + 2,                y + 6);
  doc.text("Phone",         COL.phone.x  + 2,                y + 6);
  doc.text("Amount (PKR)",  COL.amount.x + COL.amount.w / 2, y + 6, { align: "center" });
  doc.text("Status",        COL.status.x + COL.status.w / 2, y + 6, { align: "center" });

  y += ROW_H + 1;

  // ── TABLE ROWS ────────────────────────────────────────────────────────────
  // Sort: paid first, then pending
  const sortedMembers = [...members].sort((a, b) => {
    const aPaid = thisMonthPayments.find((p) => p.member_id === a.id)?.status === "paid";
    const bPaid = thisMonthPayments.find((p) => p.member_id === b.id)?.status === "paid";
    return (bPaid ? 1 : 0) - (aPaid ? 1 : 0);
  });

  sortedMembers.forEach((member, idx) => {
    const payment = thisMonthPayments.find((p) => p.member_id === member.id);
    const isPaid  = payment?.status === "paid";
    const rowBg   = idx % 2 === 0 ? WHITE : GRAY_100;

    // Row background
    doc.setFillColor(...rowBg);
    doc.rect(ML, y, CW, ROW_H, "F");

    // Left accent bar for paid rows
    if (isPaid) {
      doc.setFillColor(...GREEN);
      doc.rect(ML, y, 1.5, ROW_H, "F");
    }

    // Row number
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...GRAY_400);
    doc.text(String(idx + 1), COL.num.x + COL.num.w / 2, y + 6, { align: "center" });

    // Member name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...GRAY_900);
    // Truncate long names
    const nameStr = member.name.length > 22 ? member.name.slice(0, 21) + "…" : member.name;
    doc.text(nameStr, COL.name.x + 2, y + 6);

    // Phone
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...GRAY_600);
    doc.text(member.phone, COL.phone.x + 2, y + 6);

    // Amount
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...GRAY_900);
    doc.text(
      kameti.monthly_amount.toLocaleString("en-PK"),
      COL.amount.x + COL.amount.w / 2,
      y + 6,
      { align: "center" }
    );

    // Status badge
    const badgeW   = 24;
    const badgeH   = 6;
    const badgeX   = COL.status.x + (COL.status.w - badgeW) / 2;
    const badgeY   = y + (ROW_H - badgeH) / 2;

    if (isPaid) {
      // Green filled badge
      doc.setFillColor(...GREEN);
      doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 1.5, 1.5, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.setTextColor(...WHITE);
      doc.text("PAID", badgeX + badgeW / 2, badgeY + 4.1, { align: "center" });
    } else {
      // Red outline badge
      doc.setFillColor(...RED_LIGHT);
      doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 1.5, 1.5, "F");
      doc.setDrawColor(...RED);
      doc.setLineWidth(0.4);
      doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 1.5, 1.5, "S");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.setTextColor(...RED);
      doc.text("PENDING", badgeX + badgeW / 2, badgeY + 4.1, { align: "center" });
    }

    // Row bottom border
    doc.setDrawColor(229, 231, 235); // gray-200
    doc.setLineWidth(0.2);
    doc.line(ML, y + ROW_H, PW - MR, y + ROW_H);

    y += ROW_H;
  });

  y += 6;

  // ── FOOTER SUMMARY CARD ───────────────────────────────────────────────────
  // Check if we need a new page
  if (y + 40 > PH - 20) {
    doc.addPage();
    y = 20;
  }

  doc.setDrawColor(...GREEN_MID);
  doc.setLineWidth(0.5);
  doc.line(ML, y, PW - MR, y);
  y += 6;

  // Summary row — two stat boxes
  const boxW = (CW - 6) / 2;

  // Box 1: Members paid
  doc.setFillColor(...GREEN_LIGHT);
  doc.roundedRect(ML, y, boxW, 18, 2, 2, "F");
  doc.setDrawColor(...GREEN_MID);
  doc.setLineWidth(0.3);
  doc.roundedRect(ML, y, boxW, 18, 2, 2, "S");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...GRAY_600);
  doc.text("Members Paid This Month", ML + boxW / 2, y + 6, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...GREEN);
  doc.text(`${paidCount} / ${totalCount}`, ML + boxW / 2, y + 14, { align: "center" });

  // Box 2: Total collected
  const box2X = ML + boxW + 6;
  doc.setFillColor(...AMBER_LIGHT);
  doc.roundedRect(box2X, y, boxW, 18, 2, 2, "F");
  doc.setDrawColor(253, 230, 138); // amber-200
  doc.setLineWidth(0.3);
  doc.roundedRect(box2X, y, boxW, 18, 2, 2, "S");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...GRAY_600);
  doc.text("Total Collected", box2X + boxW / 2, y + 6, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...AMBER);
  doc.text(formatPKR(totalCollected), box2X + boxW / 2, y + 14, { align: "center" });

  y += 26;

  // ── PAGE FOOTER ───────────────────────────────────────────────────────────
  const footerY = PH - 12;

  doc.setFillColor(...GREEN);
  doc.rect(0, footerY - 4, PW, 16, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(187, 247, 208);
  doc.text("Generated by KametiPro  ·  kametipro.vercel.app", PW / 2, footerY + 3, { align: "center" });

  // Page number
  doc.setTextColor(187, 247, 208);
  doc.text(`Page 1`, PW - MR, footerY + 3, { align: "right" });

  // ── SAVE ─────────────────────────────────────────────────────────────────
  const fileName = `${slugify(kameti.name)}-${slugify(monthName)}-Report.pdf`;
  doc.save(fileName);
}
